#String operations:

str1="Python Program"
str2="string Operations"
print(f"Length of the str1 1 is:{len(str1)} and that of str2 is:{len(str2)}")
print(f"string concatenation{str1+str2}")
print(f"string repeatation:{str2*3}")
print("First element of string 2 is:",str2[0])
print("\nPerforming String slicing:\n")
print(str1[2:9])
print(str1[2:9:2])
print(str2[6:])
print(str2[:9:1])
print(str2[::-1])
print(f"Str1 in lower case is:{str2.lower()} and str2 in lower case is:{str2.lower()}")
print(f"Str1 in upper case is:{str2.upper()} and str2 in upper case is:{str2.upper()}")
print("str1 starts with Python:",str1.startswith("Python"))
print("str2 ends with Python:",str1.endswith("operations"))
print(str1.isalpha())
print(str1.isalnum())
print(str2.isspace())
print(str2.capitalize())
print("\nSplit operations:\n")
print(str1.split())
print(str2.split(" "))
print(str1.find('Pro'))
print(str1.index("Pro"))
print(str1.find('o',4,14))
print(str2.count('i'))
print("--------------------------------------------------------------------------")